# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/
###
# Welcome to the new js2coffee 2.0, now
# rewritten to use the esprima parser.
# try it out!
###
$('#formValidate').validate
  rules:
    username:
      required: "true"
      minlength: "5"
    email:
      required: "true"
      email: "true"
    password:
      required: "true"
      minlength: "5"
    confirmpassword:
      required: "true"
      minlength: "5"
      equalTo: '#password'
# ---
# generated by js2coffee 2.2.0